In [8]:
import pandas as pd
import numpy as np

In [15]:
df_review = pd.read_csv('data/IMDB Dataset.csv')
df_review

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [16]:
df_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [17]:
df_positive = df_review[df_review['sentiment']=='positive'][:9000]
df_positive

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
4      Petter Mattei's "Love in the Time of Money" is...  positive
5      Probably my all-time favorite movie, a story o...  positive
...                                                  ...       ...
18187  The Sea Is Watching has been made from an orig...  positive
18188  I used to watch this show when I was a little ...  positive
18189  John Leguizamo's one man show is both funnier ...  positive
18192  in a not so conventional sense of the word.<br...  positive
18195  This movie brings back so many memories for me...  positive

[9000 rows x 2 columns]

In [18]:
df_negative = df_review[df_review['sentiment'] == 'negative'][:1000]
df_negative

                                                 review sentiment
3     Basically there's a family where a little boy ...  negative
7     This show was an amazing, fresh & innovative i...  negative
8     Encouraged by the positive comments about this...  negative
10    Phil the Alien is one of those quirky films wh...  negative
11    I saw this movie when I was about 12 when it c...  negative
...                                                 ...       ...
2000  Stranded in Space (1972) MST3K version - a ver...  negative
2005  I happened to catch this supposed "horror" fli...  negative
2007  waste of 1h45 this nasty little film is one to...  negative
2010  Warning: This could spoil your movie. Watch it...  negative
2013  Quite what the producers of this appalling ada...  negative

[1000 rows x 2 columns]

In [21]:
df_review_imb = pd.concat([df_positive, df_negative])
df_review_imb

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
4     Petter Mattei's "Love in the Time of Money" is...  positive
5     Probably my all-time favorite movie, a story o...  positive
...                                                 ...       ...
2000  Stranded in Space (1972) MST3K version - a ver...  negative
2005  I happened to catch this supposed "horror" fli...  negative
2007  waste of 1h45 this nasty little film is one to...  negative
2010  Warning: This could spoil your movie. Watch it...  negative
2013  Quite what the producers of this appalling ada...  negative

[10000 rows x 2 columns]